# Generated by Django 3.2.4 on 2021-07-25 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcode',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록시간'),
            preserve_default=False,
        ),
    ]
