# Generated by Django 3.2.4 on 2021-07-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showing_app', '0002_passcode_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passcode',
            name='time',
        ),
    ]
